### ISSUE TITLE
Progress % to the bot is hit and miss

### ISSUE THREAD

**Issue by markwal** [markwal/OctoPrint-GPX#10]
Steps:
1. Start a non-SD card print from OctoPrint

Expected result:
Progress percentage to show on the LCD

Actual result:
Sometimes % is shown, sometimes it shows 0% the whole time

**Comment by chuckmitchell** [comment]
I haven't seen this happen yet.
Can you send me a file to print and test?

**Comment by markwal** [comment]
I think I have it fixed in 2.4.1.  There were several issues, but the most recent one I fixed is if the gcode filename started with a number, the progress was broken.
