### ISSUE TITLE
Failed Install

### ISSUE THREAD

**Issue by jrpmedia** [markwal/OctoPrint-GPX#18]
I'm not a guru so here is the install log for My RPi Model B using OctoPrint: 1.2.10

OctoPrint
         Settings 
         System  
         pi  
 Connection
Serial Port
AUTO/dev/ttyACM0
Baudrate
AUTO2500002304001152005760038400192009600
Printer Profile
Default

Save connection settings

Auto-connect on server startup
Connect
 State
Machine State: Error: Failed to autodetect serial port, please set it manually.
File:  
Timelapse: -
Approx. Total Print Time: -
Print Time: -
Print Time Left: -
Printed: -

 Print
 Pause
 Cancel
 Files

Free: 5.5GB / Total: 7.0GB
 Upload

 Upload to SD

Hint: You can also drag and drop files on this page to upload them.
        Temperature 
        Control 
        GCode Viewer 
        Terminal 
        Timelapse 

0
50
100
150
200
250
300

Actual T: -

Target T: -

Actual Bed: -

Target Bed: -

Actual
Target
Offset
Hotend
off
 °C Set 
 °C Set
Bed
off
 °C Set 
 °C Set
    • Version: 1.2.10 (master branch)
    •  Homepage  Sourcecode  Documentation  Bugs and Requests

Unhandled communication error
The was an unhandled error while talking to the printer. Due to that OctoPrint disconnected. Error: Failed to autodetect serial port, please set it manually.
×
OctoPrint Settings
        PRINTER
        Serial Connection 
        Printer Profiles 
        Temperatures 
        Terminal Filters 
        GCODE Scripts 
        FEATURES
        Features 
        Webcam 
        Access Control 
        API 
        OCTOPRINT
        Server 
        Folders 
        Appearance 
        Logs 
        Plugin Manager 
        Software Update 
        PLUGINS
        CuraEngine (<= 15.04) 

Installed Plugins
Name
Actions
CuraEngine (<= 15.04) 
Adds support for slicing via CuraEngine versions up to and including version 15.04 from within OctoPrint
 Homepage  AGPLv3  Gina Häußge  
 | 
Discovery 
Makes the OctoPrint instance discoverable via Bonjour/Avahi/Zeroconf and uPnP
 Homepage  AGPLv3  Gina Häußge  
 | 
Plugin Manager 
Allows installing and managing OctoPrint plugins
 Homepage  AGPLv3  Gina Häußge  
 | 
Software Update 
Allows receiving update notifications and performing updates of OctoPrint and plugins
 Homepage  AGPLv3  Gina Häußge  
 | 
Virtual Printer 
Provides a virtual printer via a virtual serial port for development and testing purposes
 AGPLv3  Gina Häußge, based on work by Daid Braam  
 | 
    •     •     • «  1  » 
Get More...
Using pip at "/home/pi/oprint/bin/pip" (Version 8.1.1)
Cancel Save

Everything is up-to-date
×
Install new Plugins...
... from the Plugin Repository

Sadly the repository is currently not available
Is your OctoPrint installation connected to the internet?
... from URL

Install
... from an uploaded archive
Browse...

Install
This does not look like a valid plugin archive. Valid plugin archives should be either zip files or tarballs and have the extension ".zip", ".tar.gz", ".tgz" or ".tar"
 Advanced options
Close

×
Installing plugin...
Installing plugin from uploaded archive...
/home/pi/oprint/bin/pip install /tmp/tmpJaFjM6.zip
Processing /tmp/tmpJaFjM6.zip
Requirement already satisfied (use --upgrade to upgrade): OctoPrint in /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.10-py2.7.egg (from OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): flask<0.11,>=0.9 in /home/pi/oprint/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): werkzeug==0.8.3 in /home/pi/oprint/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): tornado==4.0.1 in /home/pi/oprint/lib/python2.7/site-packages/tornado-4.0.1-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): sockjs-tornado==1.0.1 in /home/pi/oprint/lib/python2.7/site-packages/sockjs_tornado-1.0.1-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in /home/pi/oprint/lib/python2.7/site-packages/PyYAML-3.10-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): Flask-Login==0.2.2 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Login-0.2.2-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): Flask-Principal==0.3.5 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Principal-0.3.5-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): Flask-Babel==0.9 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Babel-0.9-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): Flask-Assets==0.10 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Assets-0.10-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): pyserial==2.7 in /home/pi/oprint/lib/python2.7/site-packages/pyserial-2.7-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): netaddr==0.7.17 in /home/pi/oprint/lib/python2.7/site-packages/netaddr-0.7.17-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): watchdog==0.8.3 in /home/pi/oprint/lib/python2.7/site-packages/watchdog-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): sarge==0.1.4 in /home/pi/oprint/lib/python2.7/site-packages/sarge-0.1.4-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): netifaces==0.10 in /home/pi/oprint/lib/python2.7/site-packages/netifaces-0.10.0-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): pylru==1.0.9 in /home/pi/oprint/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): rsa==3.2 in /home/pi/oprint/lib/python2.7/site-packages/rsa-3.2-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): pkginfo==1.2.1 in /home/pi/oprint/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /home/pi/oprint/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): semantic-version==2.4.2 in /home/pi/oprint/lib/python2.7/site-packages/semantic_version-2.4.2-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): psutil==3.2.1 in /home/pi/oprint/lib/python2.7/site-packages/psutil-3.2.1-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): awesome-slugify<1.7,>=1.6.5 in /home/pi/oprint/lib/python2.7/site-packages/awesome_slugify-1.6.5-py2.7.egg (from OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /home/pi/oprint/lib/python2.7/site-packages/Jinja2-2.8-py2.7.egg (from flask<0.11,>=0.9->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /home/pi/oprint/lib/python2.7/site-packages/itsdangerous-0.24-py2.7.egg (from flask<0.11,>=0.9->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): certifi in /home/pi/oprint/lib/python2.7/site-packages/certifi-2016.02.28-py2.7.egg (from tornado==4.0.1->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /home/pi/oprint/lib/python2.7/site-packages/backports.ssl_match_hostname-3.5.0.1-py2.7.egg (from tornado==4.0.1->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): blinker in /home/pi/oprint/lib/python2.7/site-packages/blinker-1.4-py2.7.egg (from Flask-Principal==0.3.5->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): Babel>=1.0 in /home/pi/oprint/lib/python2.7/site-packages/Babel-2.3.3-py2.7.egg (from Flask-Babel==0.9->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): speaklater>=1.2 in /home/pi/oprint/lib/python2.7/site-packages/speaklater-1.3-py2.7.egg (from Flask-Babel==0.9->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): webassets>=0.10 in /home/pi/oprint/lib/python2.7/site-packages/webassets-0.11.1-py2.7.egg (from Flask-Assets==0.10->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in /home/pi/oprint/lib/python2.7/site-packages/argh-0.26.1-py2.7.egg (from watchdog==0.8.3->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /home/pi/oprint/lib/python2.7/site-packages/pathtools-0.1.2-py2.7.egg (from watchdog==0.8.3->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.3 in /home/pi/oprint/lib/python2.7/site-packages (from rsa==3.2->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): regex in /home/pi/oprint/lib/python2.7/site-packages/regex-2016.04.15-py2.7-linux-armv7l.egg (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): Unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python2.7/site-packages/Unidecode-0.04.19-py2.7.egg (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /home/pi/oprint/lib/python2.7/site-packages/MarkupSafe-0.23-py2.7-linux-armv7l.egg (from Jinja2>=2.4->flask<0.11,>=0.9->OctoPrint->OctoPrint-GPX==2.5.2)
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in /home/pi/oprint/lib/python2.7/site-packages/pytz-2016.3-py2.7.egg (from Babel>=1.0->Flask-Babel==0.9->OctoPrint->OctoPrint-GPX==2.5.2)
Installing collected packages: OctoPrint-GPX
Running setup.py install for OctoPrint-GPX: started
Command "/home/pi/oprint/bin/python2 -u -c "import setuptools, tokenize;**file**='/tmp/pip-cHYVSX-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-k1EEDg-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/oprint/include/site/python2.7/OctoPrint-GPX" failed with error code 1 in /tmp/pip-cHYVSX-build/
Running setup.py install for OctoPrint-GPX: finished with status 'error'
Complete output from command /home/pi/oprint/bin/python2 -u -c "import setuptools, tokenize;**file**='/tmp/pip-cHYVSX-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-k1EEDg-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/oprint/include/site/python2.7/OctoPrint-GPX:
running install
running build
got version from expanded keyword {'version': '2.5.2', 'full': '5f537dfb75472780103714f1e9bc6abe4e3bfb5d'}
running build_py
creating build
creating build/lib.linux-armv6l-2.7
creating build/lib.linux-armv6l-2.7/octoprint_GPX
copying octoprint_GPX/**init**.py -> build/lib.linux-armv6l-2.7/octoprint_GPX
copying octoprint_GPX/_version.py -> build/lib.linux-armv6l-2.7/octoprint_GPX
copying octoprint_GPX/iniparser.py -> build/lib.linux-armv6l-2.7/octoprint_GPX
copying octoprint_GPX/gpxprinter.py -> build/lib.linux-armv6l-2.7/octoprint_GPX
running egg_info
creating OctoPrint_GPX.egg-info
writing requirements to OctoPrint_GPX.egg-info/requires.txt
writing OctoPrint_GPX.egg-info/PKG-INFO
writing top-level names to OctoPrint_GPX.egg-info/top_level.txt
writing dependency_links to OctoPrint_GPX.egg-info/dependency_links.txt
writing entry points to OctoPrint_GPX.egg-info/entry_points.txt
writing manifest file 'OctoPrint_GPX.egg-info/SOURCES.txt'
warning: manifest_maker: standard file '-c' not found

reading manifest file 'OctoPrint_GPX.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '_.h' under directory 'GPX'
warning: no previously-included files matching '_' found under directory 'GPX/build'
warning: no files found matching 'GPX/build/src/shared/config.h'
writing manifest file 'OctoPrint_GPX.egg-info/SOURCES.txt'
creating build/lib.linux-armv6l-2.7/octoprint_GPX/static
creating build/lib.linux-armv6l-2.7/octoprint_GPX/static/css
copying octoprint_GPX/static/css/gpx.css -> build/lib.linux-armv6l-2.7/octoprint_GPX/static/css
creating build/lib.linux-armv6l-2.7/octoprint_GPX/static/js
copying octoprint_GPX/static/js/gpx.js -> build/lib.linux-armv6l-2.7/octoprint_GPX/static/js
creating build/lib.linux-armv6l-2.7/octoprint_GPX/static/less
copying octoprint_GPX/static/less/gpx.less -> build/lib.linux-armv6l-2.7/octoprint_GPX/static/less
creating build/lib.linux-armv6l-2.7/octoprint_GPX/templates
copying octoprint_GPX/templates/GPX_settings.jinja2 -> build/lib.linux-armv6l-2.7/octoprint_GPX/templates
copying octoprint_GPX/static/less/Makefile -> build/lib.linux-armv6l-2.7/octoprint_GPX/static/less
running build_ext
building 'gpx' extension
creating build/temp.linux-armv6l-2.7
creating build/temp.linux-armv6l-2.7/GPX
creating build/temp.linux-armv6l-2.7/GPX/src
creating build/temp.linux-armv6l-2.7/GPX/src/pymodule
creating build/temp.linux-armv6l-2.7/GPX/src/shared
creating build/temp.linux-armv6l-2.7/GPX/src/gpx
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c GPX/src/pymodule/gpxmodule.c -o build/temp.linux-armv6l-2.7/GPX/src/pymodule/gpxmodule.o -DGPX_VERSION="\"OctoPrint\"" -DSERIAL_SUPPORT -fvisibility=hidden -IGPX/build/src/shared -IGPX/src/shared -IGPX/src/gpx
arm-linux-gnueabihf-gcc: error: GPX/src/pymodule/gpxmodule.c: No such file or directory
arm-linux-gnueabihf-gcc: fatal error: no input files
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 4

---

Done!
Close

Something went wrong
Installing the plugin from URL "unknown" failed: Could not parse output from pip

**Comment by markwal** [comment]
If I recall correctly you solved this via a thread on Google Groups?

**Comment by DaAwesomeP** [comment]
> Error: Failed to autodetect serial port, please set it manually.

There's your problem. You need to select the baudrate manually instead of using the `AUTODETECT` option.
