### ISSUE TITLE
Octoprint z-changes

### ISSUE THREAD

**Issue by Jabarnes01** [markwal/OctoPrint-GPX#39]
We are seeing a problem with our replicator 2 where the z-change event is not firing. Sometimes it does but only after the 4th z-change. Does anyone else experience this issue?

**Comment by markwal** [comment]
What event do you mean?  Did you write a plugin that is listening for an event?  Or do you mean the command line's tied to events via config.yaml?  Or do you mean that the timelapse pictures aren't being taken?

There is a setting that specifies the minimum Z change required to do some of those things.  That setting is to prevent Z-lift (slicer feature) from triggering a layer change event.  Perhaps your layer height is 1/4 of the minimum Z change?

**Comment by markwal** [comment]
I'm closing this for now, but feel free to add more info and I'll reopen.
