### ISSUE TITLE
Cant install plugin

### ISSUE THREAD

**Issue by ilisei** [markwal/OctoPrint-GPX#44]
When i have install plugin, octoprint get error. "Could not find a version that satisfies the requirement OctoPrint (from OctoPrint-GPX==2.5.5) (from versions: )
No matching distribution found for OctoPrint (from OctoPrint-GPX==2.5.5)"

**Comment by markwal** [comment]
Are you installing OctoPrint-GPX plugin from the plugin manager in OctoPrint->Settings?

What it sounds like is that you're installing the plugin without activating OctoPrint's virtual environment.
