### ISSUE TITLE
Plugin Install Error

### ISSUE THREAD

**Issue by igranderojo** [markwal/OctoPrint-GPX#52]
arm-linux-gnueabihf-gcc: error: GPX/src/pymodule/gpxmodule.c: No such file or directory
arm-linux-gnueabihf-gcc: fatal error: no input files
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 4
>>>>>>>>>>>>>>>>>>>>>

I downloaded the ZIP file, opened Octoprint on Pi, then "browse", then "install", then long list of commands that appeared to all work, no errors, until the above error was listed and the install stopped.
[PluginError copy.txt](https://github.com/markwal/OctoPrint-GPX/files/1540787/PluginError.copy.txt)

**Comment by markwal** [comment]
Github's archive doesn't include all the necessary files (and not much I can do about that, it's just the way github archives work).  You need to use one of the releases or just install it from OctoPrint's plugin manager by clicking "Get more..." and searching for GPX.
