### ISSUE TITLE
Makerbot Rep2 gcode not on build plate

### ISSUE THREAD

**Issue by igranderojo** [markwal/OctoPrint-GPX#53]
Octoprint working, downloaded and installed plugin for GPX successfully
Setup profile for Makerbot Rep2
Connection to Pi works and opens Octorprint.
Connection to Makerbot Rep2 works, can control printer movement.

Issue:
Sliced a file in Cura 2.5.0 for MacBook Pro saved gcode.
uploaded gcode to Octoprint.
the object was at the center of the build plate in Cura, but not in Octoprint.
How can I get the object onto the build plate?
Thank you

**Comment by markwal** [comment]
Cura and most of the reprap world call the front left corner (0,0) so the center of the build plate is something like (112, 72) (that's actually Rep 1, Rep 2 is similarly non-zero).  You have to tell Cura that the center of the build plate is 0,0 like with a delta printer.  It's in the machine settings.  "Origin at center" should be checked.
