### ISSUE TITLE
Can't update to Version 0.3.8

### ISSUE THREAD

**Issue by Helisinus** [markwal/OctoPrint-GPX#7]
Hi, 
today i did a fresh install on a new octopi installation. After this i had a installed version 0.3.7. This version works, but i get an update information for a new version 0.3.8. If i klick update, it seems the new Version will be installed and Octopi writes me i have to restart Octoprint to use the new version. But after the restart, i always have a version 0.3.7 and get the update message again.
Is there a other way to update this version?

Regards 
Joerg

**Comment by markwal** [comment]
I think this may be a bug in how the plugin interacts with the softwareupdate plugin and pre-releases.  That is, I think this turns up when the most recent release is marked "pre-release", but since 0.3.7 was before I did the opt-in for pre-releases, it may be because the 0.3.7 plugin is answering that question wrong.

I've posted a new release 0.3.9 that contains several other fixes as well as the pre-release opt-in.  I just tried it out with softwareupdate and it appears to work.  This issue may come back the next time I post a pre-release update, but I'll be watching for it.

You may have to force the software update plugin to refresh its cache:
- Settings->Software Update->Advanced options->Force check for update (overrides cache)

**Comment by Helisinus** [comment]
Sorry, but this didn't work for me. After Force check for update (overrides cache) i get the Message there ist a new version 0.3.9 available, and after installing this version, i got a message the update was successful and i have to restart octopring. But after restart octorprint or the hole raspberry the is still version 0.3.7 installed

**Comment by Helisinus** [comment]
So, i have to correct my answer. In Software update the installed Version is shown as 0.3.7 and if i search for updates i will find every try the new Version. But in the Pluginmanager the Plugin was shown as version 0.3.9

**Comment by markwal** [comment]
Hmmm...  The 0.3.7 local version in software update is stored in the software update plugin cache.  If you do that force check for update again (after the update), I think that will update the cache and it should match then the pluginmanager.

Ther purpose of that persisted cache is to avoid too many calls to the github API that is rate limited, but the cache also stores the local version.  Perhaps I'm doing something wrong in the plugin that prevents the software update plugin from updating its cache of local versions after an update is installed.

**Comment by markwal** [comment]
What version of OctoPrint are you running?  It's in the lower left hand corner of the page.  Be sure to send the whole line including the parenthetical.

**Comment by Helisinus** [comment]
There is only the Versionnumer Version: 1.2.2 (master branch) without parentheticat.
This is a new installation from yesterday an after the installation i did the updatet.
On my other (older) system is the thame after the update, only Version: 1.2.2 (master branch). no more information.
The system uses the version 0.3.9 but the updatedmanager thinks i use the version 0.3.7

**Comment by Helisinus** [comment]
Here are a few screenshots:
![version](https://cloud.githubusercontent.com/assets/11804790/8510325/0f43d760-22df-11e5-9b9c-39356e675019.JPG)
![pluginmanager](https://cloud.githubusercontent.com/assets/11804790/8510327/0f47f4bc-22df-11e5-99d5-9c1d501705c0.JPG)
![softwareupdate](https://cloud.githubusercontent.com/assets/11804790/8510326/0f47f7b4-22df-11e5-812e-9802d44722ac.JPG)

**Comment by markwal** [comment]
OK, this turns out to be fixed in the next version of the software update plugin.  A work around for now is to delete the the line plugins > softwareupdate > _config_version from config.yaml.

config.yaml is in ~/.octoprint

You're looking for the _config_version line in the softwareupdate section of the plugins section.

**Comment by Helisinus** [comment]
o.k. this works. 
must i insert the line again when the update plugin is updatet or will the plugin insert this line ?

Thank for your fast help

**Comment by markwal** [comment]
No. The software update plugin will recreate it. You might have to delete it again next time you run into this problem, but eventually you will get a new version of software update plugin that will fix it for good.

Sent from my Windows Phone

**Comment by Helisinus** [comment]
o.k.
Thanks for your help :-)

**Comment by foosel** [comment]
For anyone else running into this problem, paste this

```
[["remove", "plugins.softwareupdate._config_version", ""]]
```

into [the Yamlpatcher plugin](http://plugins.octoprint.org/plugins/yamlpatcher/).

![image](https://cloud.githubusercontent.com/assets/83657/8575387/063e615c-259c-11e5-8ec8-a13fdc075032.png)

**Comment by Helisinus** [comment]
Sorry, but this dosen't work for me. Maybe i did something wrong.
See the attached Screenshots
![octo2](https://cloud.githubusercontent.com/assets/11804790/8580225/bde28474-25b9-11e5-86c9-902684276816.JPG)
![octo1](https://cloud.githubusercontent.com/assets/11804790/8580224/bde26084-25b9-11e5-8a5e-a326793d1d77.JPG)

**Comment by foosel** [comment]
Don't close the settings dialog with save after you did that, just directly reboot. I'll release 1.2.3 probably tomorrow which should solve that issue for good though.

**Comment by Helisinus** [comment]
I tryed the rebbot after pressing apply, But no success. Also if i delete the  line  _config_version  in config.yaml manualy. the update dont work. i have installed 0.3.9 and available is 0.3.10 and will not be installed. After a reboot the line _config_version was back in config.yaml.
But no matter, i will wait for the new Veriso 1.2.3 and try it again.

Thanks for your help

Joerg
