### ISSUE TITLE
Replicator 2 Prints Mid Air

### ISSUE THREAD

**Issue by 400HPMustang** [markwal/OctoPrint-GPX#70]
**Printer**
Makerbot Replicator 2

**Platform**
Octoprint 1.3.11

**Reproduction Steps**

1. Activate Makerbot in Cura
2. Add Model
3. Slice
4. Hit Print with Octoprint

**Actual Results**

- Nozzle heats to temperature
- Build plate moves up then all the way down but doesn't stop at the bottom. It tries to moved own further for a bit then moves back up a few inches. 
- Extruder starts extruding filament into the air as though it were printing on the build plate. 

**Expected Results**
- Nozzle heats to temperature
- Build plate homes
- Extruder primes/wipes
- Nozzle moves to start position
- Print succeeds

**Additional Information**
This happens with Cura 3.6.0 and 4.2. Seems to happen regardless of whether the print is sent over Octoprint or via SD card. Octoprint does connect to the printer and provides control over the printer and display settings. 

![OctoPrint_GPX_EEPROM_Warn](https://user-images.githubusercontent.com/45641587/62163312-bd023380-b2df-11e9-9647-9be91523c044.png)

![Cura_Makerbot_Preferences](https://user-images.githubusercontent.com/45641587/62163314-bd023380-b2df-11e9-99dc-394d02c1a640.png)

![OctoPrint_GPX_Settings](https://user-images.githubusercontent.com/45641587/62163315-bd023380-b2df-11e9-8c7c-eb8420ca01c8.png)

**Comment by rpavlik** [comment]
From what you've described, this is an issue with your Cura settings, and not with this OctoPrint plugin.

**Comment by 400HPMustang** [comment]
Thanks.
