### ISSUE TITLE
can you add creator 3 and Guider 2

### ISSUE THREAD

**Issue by goldjunge91** [markwal/OctoPrint-GPX#79]
Hi,
can you add the 2 printer  from flashforge ? Creator3 and guider 2

thx

**Comment by markwal** [comment]
These two printers are not running Sailfish firmware and I don't think they use the x3g protocol any more.  There is another plugin that is for later FlashForge printers, let me look it up.  Just a sec...

**Comment by markwal** [comment]
https://plugins.octoprint.org/plugins/FlashForge/
https://github.com/Mrnt/OctoPrint-FlashForge
